export const conceptos = [
  {
    id: 'reingenieria',
    title: 'Reingeniería',
    content: [
      { type: 'paragraph', text: 'Es el proceso de analizar y modificar sistemas de softwares existentes para mejorar su calidad, su rendimiento, funcionalidad o para adaptarlos a nuevas necesidades y tecnologías.' },
      { type: 'subtitle', text: 'Incluye actividades' },
      { type: 'paragraph', text: 'Reingeniería de software, la refactorización del código, la migración a nuevas plataformas, y la incorporación de buenas practicas de desarrollo, manteniendo el sistema operativo durante el proceso.' },
      { type: 'subtitle', text: '¿Qué es un proceso?' },
      { type: 'paragraph', text: 'Es un conjunto de actividades planificadas que implican la participación de un numero de personas y de recursos materiales coordinados para conseguir un objetivo.' },
      { type: 'subtitle', text: '¿Qué es la reingeniería?' },
      { type: 'paragraph', text: 'Ingeniería es el uso de principios científicos para diseñar y construir maquinas, sistemas productos y procesos. Es una profesión basada en el uso de los conocimientos científicos para transformar ideas en acción. A diferencias de las ciencias puras cuyo objetivo es el conocimiento por el conocimiento en si mismo, la ingeniería se basa en la aplicación del conocimiento científico en la solución de problemas reales.' },
      { type: 'paragraph', text: 'Replanteamiento y rediseño de los procesos y sistemas para lograr mejoras.' },
      { type: 'subtitle', text: '¿Por qué hacer reingeniería de software?' },
      { type: 'paragraph', text: 'La reingeniería de procesos es el rediseño radical de los procesos de negocio para lograr mejoras dramáticas en la productividad, de los ciclos y de la calidad.' },
      { type: 'subtitle', text: '¿Qué empresas aplican la reingeniería de procesos?' },
      { type: 'list', items: ['Con problemas', 'Que se anticipan', 'En optimas condiciones'] },
      { type: 'subtitle', text: 'Visión y Objetivos' },
      { type: 'list', items: ['Análisis de procesos existentes', 'Identificar procesos existentes', 'Implementar el nuevo proceso', 'Hacer los nuevos procesos operacionales', 'Evaluar el nuevo proceso', 'Mejoramiento continuo'] },
      { type: 'subtitle', text: 'Pasos' },
      { type: 'list', items: ['Definir objetivos y marco de trabajo', 'Identificar las necesidades del cliente', 'Estudiar los procesos actuales', 'Formular un plan de negocio de rediseño', 'Implementar el rediseño'] },
      { type: 'subtitle', text: 'Procesos Medulares' },
      { type: 'paragraph', text: 'Usualmente las empresas deberían tener 6 procesos generales:' },
      { type: 'list', items: ['Compra', 'Manufactura', 'Ventas', 'Distribución', 'Mercadotecnia', 'Administración'] },
      { type: 'subtitle', text: 'Porque un enfoque en procesos' },
      { type: 'paragraph', text: 'Proceso: es un conjunto de fases sucesivas de un fenómeno o hecho complejo. Secuencia de acciones que se llevan a cabo para lograr un fin determinado. Este concepto es aplicable a muchos ámbitos. Un proceso es un conjunto de actividades planificadas que implican la participación de un numero de personas y de recursos materiales coordinados para conseguir un objetivo previamente identificado.' },
      { type: 'subtitle', text: 'Crisis del software' },
      { type: 'paragraph', text: 'La crisis del software es un termino informático acuñado. Uno de los principales problemas en el desarrollo de software es que muchos proyectos empiezan la programación tan pronto "lo definen" y concentran la mayor parte de su esfuerzo en la escritura de código.' },
      { type: 'subtitle', text: 'Síntomas del software en crisis' },
      { type: 'list', items: ['Baja funcionalidad en el software', 'Funcionalidad incorrecta', 'Diseño poco estructurado', 'Impresión en la planificación del proyecto', 'Confiabilidad cuestionable', 'Altos requerimientos de personal para desarrollo y mantenimiento'] },
      { type: 'subtitle', text: 'Mitos que afectan un buen desarrollo' },
      { type: 'list', items: ['Basta con tener estándares y procedimientos', 'Lo importante es manejar tecnología de punta', 'Estamos atrasados, pero con mas gente y nos recuperamos', 'Debemos programar inmediatamente', 'Los cambios son fáciles', 'El código es el único producto'] },
      { type: 'subtitle', text: 'Reingeniería en las TICS' },
      { type: 'paragraph', text: 'Reingeniería en las TICS (Tecnologías de la información y comunicación) es un enfoque estratégico y sistemático que se utiliza para mejorar, optimizar y transformar los procesos, sistemas y servicios relacionados con la tecnología de la información dentro de una organización. Implica revisar críticamente los sistemas existentes, los procesos de negocio y la infraestructura tecnológica de una empresa con el fin de identificar áreas de mejora y aplicar cambios significativos que generen valor y mejorar la eficiencia.' },
      { type: 'subtitle', text: 'La reingeniería de las TIC se centra en varios aspectos claves:' },
      { type: 'list', items: [
          { title: '1.- Procesos de negocio', text: 'Se analiza y se redefinen los procesos de negocio existentes para alinearlos mejor con los objetivos estratégicos de la organización y aprovechar las capacidades de las TIC para mejorar la eficiencia, la calidad y la velocidad de ejecución.' },
          { title: '2.- Sistemas de información', text: 'Se revisan y se mejoran los sistemas de información existentes como ERP, CRM , SCM, sistemas de gestión de documentos, entre otros. Se pueden implementar nuevas tecnologías o actualizar las existentes para optimizar el rendimiento y la funcionalidad.' },
          { title: '3.- Infraestructura tecnológica', text: 'Se evalúa y se moderniza la infraestructura tecnológica de la organización, incluyendo: Redes, Servidores, Almacenamiento, Seguridad informática y Servicios en la nube. Se busca mejorar la disponibilidad, la escalabilidad, la seguridad y la eficiencia de los recursos tecnológicos de la empresa.' },
          { title: '4.- Gestión del cambio', text: 'Se implementan medidas para gestionar el cambio organizacional que con lleva la reingeniería de las TIC. Esto puede incluir: Capacitación del personal, Comunicación efectiva, Participación de los empleados, Gestión de resistencias. Para garantizar una transición exitosa hacia los nuevos procesos y sistemas.' },
          { title: '5.- Gestión del rendimiento', text: 'Se establecen indicadores clave de rendimiento (KPIs) para medir y monitorear el éxito de la reingeniería de las TIC. Esto permite evaluar el impacto de los cambios realizados y realizar ajustes según sea necesario para garantizar que se alcancen los objetivos establecidos.' }
      ]},
      { type: 'subtitle', text: 'Procesos de negocio' },
      { type: 'paragraph', text: 'Los procesos de negocio son secuencia de actividades interrelacionadas que se llevan a cabo dentro de una organización para lograr el objetivo especifico. Estas actividades están diseñadas para transformar entradas(insumos) en resultados (productos o servicios) que agregan valor a la organización y a sus clientes. Los procesos de negocio pueden ser simples o complejos y pueden abarcar varias áreas funcionales de una empresa.' },
      { type: 'subtitle', text: 'Algunas Características clave del proceso de negocio:' },
      { type: 'list', items: ['Objetivo: Cada proceso de negocio tiene un objetivo claro y específico que se debe lograr', 'Secuencia de actividades: Se componen de una serie de actividades interrelacionadas que se realizan en un orden especifico', 'Valor agregado: cada actividad dentro de un proceso de negocio debe agregar valor o acercarte a la meta final'] },
      { type: 'subtitle', text: 'Mantenimiento de Software' },
      { type: 'list', items: [
        { title: 'Mantenimiento Correctivo', text: 'Mantenimiento del sistema informático, que se realiza de un fallo o problema del mismo, con el objetivo de restablecer la operación esperada. Funcionalidad esperada: El sistema haga lo que debe hacer, lo haga correctamente, no haga lo que no debe hacer. Lista de errores.' },
        { title: 'Mantenimiento Adaptativo', text: 'Consiste en adaptar el software de un equipo para hacer frente a los cambios ocurridos en el entorno, es decir, cambios en las condiciones e influencias que actúan desde el exterior. Originado por el Hardware. Originado por el entorno (SHCP).' },
        'Mantenimiento Perfectivo',
        'Mantenimiento Preventivo'
      ]},
      { type: 'subtitle', text: 'Reingeniería de software' },
      { type: 'paragraph', text: 'La reingeniería de software es el proceso de modificar un sistema de software para mejorar su rendimiento, arquitectura, y funcionalidad, sin cambiar su comportamiento observable. Este proceso es necesario cuando el software se vuelve obsoleto o costoso de mantener debido a factores como la obsolescencia tecnológica, la complejidad del sistema o la falta de documentación.' },
      { type: 'subtitle', text: 'La importancia de la reingeniería de software' },
      { type: 'paragraph', text: 'Es fundamental porque ayuda a resolver problemas comunes que enfrentan las empresas con sus sistemas heredados, tales como:' },
      { type: 'list', items: ['Mantenimiento costoso: Los sistemas antiguos pueden ser costosos de mantener debido a la falta de documentación, las tecnologías obsoletas y los errores frecuentes.', 'Falta de flexibilidad: Los sistemas heredados pueden no ser fácilmente modificables para satisfacer nuevas necesidades del negocio.', 'Perdida de competitividad: Si el software no se actualiza, las empresas pueden quedar rezagadas frente a competidores que utilizan tecnología mas moderna.'] },
      { type: 'subtitle', text: 'Crisis del software' },
      { type: 'paragraph', text: 'Hace referencia a la incapacidad de las metodologías de desarrollo de software tradicionales para satisfacer las necesidades de las empresas en cuanto a la calidad, el tiempo de desarrollo y el presupuesto.' },
      { type: 'subtitle', text: 'Causas de las crisis' },
      { type: 'list', items: ['Falta de estándares claros', 'Escasa formación en la industria', 'Mala gestión de proyectos'] },
      { type: 'subtitle', text: 'Calidad del software' },
      { type: 'paragraph', text: 'Se refiere a la capacidad de un sistema para cumplir los requisitos establecidos, ser confiables, fácil de mantener y satisfactorio para los usuarios.' },
      { type: 'subtitle', text: 'Características de un software de calidad:' },
      { type: 'list', items: ['Fiabilidad: El sistema debe funcionar correctamente en diversas condiciones', 'Eficiencia: Debe hacer un uso adecuado de los recursos (tiempo, memoria, etc.)', 'Usabilidad: La interfaz debe ser fácil de usar', 'Mantenibilidad: Debe ser fácil de modificar y corregir errores.'] },
      { type: 'subtitle', text: 'Estándares de calidad' },
      { type: 'paragraph', text: 'Son un conjunto de normas que definen los requisitos de calidad para el desarrollo, mantenimiento y gestión de software.' },
      { type: 'list', items: ['ISO 9001: estándar para sistemas de gestión de calidad en cualquier organización', 'CMMI (Capability Maturity Model Integration): Un modelo para mejorar y evaluar los procesos de desarrollo de software', 'IEEE 829: Estándar para la documentación de pruebas de software'] },
      { type: 'subtitle', text: 'Sistemas heredados' },
      { type: 'paragraph', text: 'Los sistemas heredados son aplicaciones de software que, aunque ya no se desarrollan ni mantienen activamente, siguen en uso porque son fundamentales para las operaciones de una organización.' },
      { type: 'list', items: ['Obsolencia tecnológica', 'Falta de personal capacitado', 'Bajos niveles de documentación'] },
    ]
  },
  {
    id: 'auditoria',
    title: 'Auditoría Informática',
    content: [
        { type: 'subtitle', text: 'Introducción' },
        { type: 'paragraph', text: 'Latín: Auditor, que tiene la virtud de oír. Ejercer control sobre una determinada acción.' },
        { type: 'subtitle', text: '¿Dónde auditamos a menudo?' },
        { type: 'list', items: ['A nivel personal', 'A nivel laboral', 'A nivel académico'] },
        { type: 'subtitle', text: 'Control' },
        { type: 'paragraph', text: 'Actividad/es o acción/es realizadas por uno o varios elementos de un sistemas, que tienen como finalidad la prevención, detección y corrección de errores que afecten la homeostasis del sistema. Entradas -> Proceso -> Control -> Salidas.' },
        { type: 'paragraph', text: 'La homeostasis (del griego homoios <igual similar> y stasis <estado, estabilidad>), es una propiedad de los organismos que consiste en su capacidad de mantener una condición interna estable compensando los cambios en su entorno mediante el intercambio regulado de materia y energía con el exterior metabolismo, se trata de una forma de equilibrio dinámico que se hace posible gracias a una red de sistemas de control realimentados que constituyen los mecanismo.' },
        { type: 'paragraph', text: 'Es el examen de la información por terceras partes, personas distintas de quienes la generan y quienes la utilizan. Se produce con la intención de establecer su suficiencia y adecuación a las normas. Es necesario poder medirlas (se necesita un patrón). Produce informes como resultado del examen critico. Su objetivo es: evaluar la eficiencia y eficacia del objeto en estudio y de ser necesario determinar cursos de acción correctivos para el logro de los objetivos propuestos. Encaminar hacia la mejora continua.' },
        { type: 'subtitle', text: 'Auditoria según IMC (Instituto Mexicano de Contabilidad)' },
        { type: 'paragraph', text: 'La auditoria requiere el ejercicio de un juicio profesional, solido y maduro, para juzgar los procedimientos que deben seguirse y estimar los resultados obtenidos.' },
        { type: 'paragraph', text: 'Pregunta: Alberto es contador -> Afirmación. Alberto es responsable -> Juicio. La primera es una Afirmación, observación de lo que es verdadero para nosotros. Nos permiten describir la manera en que vemos las cosas. La segunda es un juicio, un tipo especial de declaración. Una apreciación, opinión o interpretación nuestra de lo que observamos.' },
        { type: 'subtitle', text: '¿Qué es un juicio?' },
        { type: 'list', items: ['Una declaración', 'No son verdaderos o falsos. Siempre queda abierta la posibilidad a discrepar', 'Son validos o inválidos. Su validez depende de la Autoridad que la comunidad confiera a otros para emitirlos', 'El grado de efectividad de los juicios esta directamente relacionado con la autoridad formal o informal que hemos conferido a la persona que los hace.'] },
        { type: 'subtitle', text: 'Temas relacionados' },
        { type: 'paragraph', text: 'Ontología del lenguaje: La ontología del lenguaje es una tesis desarrollada por Rafael Echeverria en su libro Ontología del lenguaje, que trata de explicar al ser humano como un ser intrínsecamente lingüístico.' },
        { type: 'paragraph', text: 'Lenguaje Generativo: El lenguaje no solo nos permite hablar "sobre" las cosas: hace que ellas sucedan. Por lo tanto, el lenguaje es acción, es generativo: crear realidades.' },
        { type: 'paragraph', text: 'Cada vez que emitimos un juicio asumimos el compromiso social de fundarlo, es decir, mostrar las observaciones en las que se asienta nuestro juicio y la inquietud o interés por el futuro que lo motiva.' },
        { type: 'subtitle', text: 'Auditoria informática' },
        { type: 'paragraph', text: 'Revisión, análisis y evaluación independiente y objetiva de un entorno informático: Hardware, Software, Base, Aplicación, Comunicaciones, Procedimientos-gestión de recursos informáticos.' },
        { type: 'subtitle', text: 'Tener en cuenta…' },
        { type: 'list', items: ['Los objetivos fijados', 'Los planes, programas y presupuestos', 'Controles, leyes aplicables, entre otros'] },
        { type: 'subtitle', text: 'Tipos de auditoria' },
        { type: 'list', items: ['Evaluación del sistema de control interno', 'De cumplimiento de políticas, estándares y procedimientos', 'De seguridad: Física y lógica', 'De operaciones/gestión', 'Interna/externa'] },
        { type: 'subtitle', text: 'Fuentes' },
        { type: 'paragraph', text: 'Todo tipo de fuente referido a: Hardware, Software, Instalaciones, Procedimientos.' },
        { type: 'subtitle', text: 'Check list' },
        { type: 'list', items: ['Revisión del Hardware', 'Revisión del Software', 'Instalaciones', 'Procedimientos'] },
        { type: 'subtitle', text: 'Clasificación de Auditorias' },
        { type: 'list', items: [
            { title: 'Desde el origen (Empresa)', text: 'Interna, Externa' },
            { title: 'Desde el origen', text: 'Primera parte (Misma Empresa), Segunda parte (Cliente -> 3ra Persona -> Proveedor), Tercera parte (SAT)' },
            { title: 'Alcance', text: 'Parciales, Globales' }
        ]},
        { type: 'paragraph', text: 'La auditoria informática es un proceso formal ejecutado por especialistas. Se orienta a la verificación y aseguramiento para que las políticas y procedimientos establecidos para el manejo y uso adecuado de las tecnologías de información en la organización se realicen de una manera oportuna y eficiente.' },
        { type: 'subtitle', text: 'Tipos de auditoria informática' },
        { type: 'list', items: [
            { title: 'Sistemas', text: 'Revisión de los sistemas de información actuales, tanto a nivel hardware como software, con objeto de descubrir potenciales puntos de mejora y determinar en que modo debería actuarse para mejorar tantos estos como otros aspectos.' },
            { title: 'Explotación', text: 'Revisión de todos los procesos encargados de producir resultados, entre ellos: La captura de la información, Los sistemas hardware de explotación, Los recursos humanos de explotación y otros.' },
            { title: 'Comunicaciones / Infraestructura', text: 'Revisión de la topología de red y determinación de posibles mejoras, análisis de caudales y grados de utilización.' },
            { title: 'Desarrollo (de software)', text: 'Revisión del proceso completo de desarrollo de proyectos por parte de la empresa auditada. El análisis se basa en cuatro aspectos fundamentales: Revisión de las metodologías utilizadas, Control interno de las aplicaciones, Satisfacción de los usuarios, Control de procesos y ejecuciones de programas críticos.' },
            { title: 'Seguridad', text: 'Abarca los conceptos de seguridad física y seguridad lógica. La seguridad física se refiere a la protección del hardware y de los soportes de datos, así como a la de los edificios e instalaciones que los albergan, contemplando las situaciones de incendios, sabotajes, robos, catástrofes naturales, etc.' },
            { title: 'Calidad (Incluyendo certificaciones)', text: '' }
        ]},
        { type: 'subtitle', text: 'Tipos de controles internos' },
        { type: 'paragraph', text: 'Los controles internos en la auditoria informática son fundamentales para garantizar la seguridad, integridad y disponibilidad de los sistemas de información en las organizaciones. Veremos los tipos y características de los controles internos, así como su implementación y relevancia en el contexto de la auditoria informática.' },
        { type: 'list', items: [
            { title: 'Preventivos', text: 'Son aquellos que tienen como objetivo evitar que ocurran errores, fraudes o accesos no autorizados antes de que sucedan. Ejemplos: Políticas de seguridad de contraseñas, Configuración de firewalls, Capacitación del personal, Validaciones de entrada de datos.' },
            { title: 'De detección', text: 'Diseñados para identificar eventos o actividades no deseadas que ya han ocurrido. Ejemplos: Sistemas de detección de intrusos (IDS), Monitoreo y registro de actividades (logs), Alertas automáticas, Revisiones periódicas.' },
            { title: 'Correctivos', text: 'Ayudan a minimizar los daños y restaurar los sistemas a un estado normal después de que se ha detectado un problema. Ejemplos: Restauración de datos desde backup, Aplicación de parches, Cambios en políticas.' }
        ]},
        { type: 'subtitle', text: 'Controles Físicos y Lógicos' },
        { type: 'list', items: [
            { title: 'Físicos', text: 'Son medidas implementadas para proteger los recursos informáticos y la infraestructura física. Ejemplos: Cerraduras, cámaras, acceso restringido, sistemas contra incendios, redundancia de energía.' },
            { title: 'Lógicos', text: 'Son medidas a nivel digital diseñadas para proteger los datos y sistemas. Ejemplos: Autenticación multifactor (MFA), encriptación, permisos y roles, antivirus.' }
        ]},
        { type: 'subtitle', text: 'Controles para el procesamiento de Datos' },
        { type: 'paragraph', text: 'Son controles implementadas para garantizar que los datos sean procesados de manera precisa, completa y oportuna.' },
        { type: 'list', items: ['Validaciones de datos', 'Revisión de cálculos automáticos', 'Conciliación de datos', 'Automatización de procesos'] },
        { type: 'subtitle', text: 'Control de Acceso y comunicaciones' },
        { type: 'paragraph', text: 'Regulan quien puede acceder a los sistemas y que acciones puede realizar.' },
        { type: 'list', items: ['Lógicos: Configuración de permisos', 'Físicos: Barreras de acceso', 'Uso de credenciales únicas', 'Sistemas de autenticación basada en roles', 'Desactivación de cuentas inactivas'] },
        { type: 'subtitle', text: 'Controles de entrada y salida' },
        { type: 'list', items: [
            { title: 'Controles de entrada', text: 'Garantizan que los datos ingresados a los sistemas sean correctos, completos y autorizados. Ejemplos: Validaciones de campos, Captcha, Verificación de identidad.' },
            { title: 'Controles de salida', text: 'Aseguran que los resultados generados por los sistemas sean precios, comprensibles y entregados solo a los usuarios autorizados. Ejemplos: Reportes con marcas de tiempo, Restricciones en impresión, Revisión automatizada.' }
        ]},
        { type: 'subtitle', text: 'Controles de copias de seguridad y de recuperación' },
        { type: 'list', items: [
            { title: 'Copias de seguridad (Backups)', text: 'Se refiere al proceso de crear duplicados de datos esenciales para su recuperación en caso de perdida. Buenas practicas: Realizar copias periódicas, almacenar en ubicaciones seguras, probar la restauración.' },
            { title: 'Recuperación de datos', text: 'Conjunto de acciones diseñadas para restaurar sistemas y datos después de un incidente. Elementos clave: Planes de recuperación (DRP), sistemas redundantes, recuperación automatizada.' },
            { title: 'Importancia', text: 'Garantizan la continuidad del negocio, mitigan efectos de incidentes, cumplen con regulaciones.' }
        ]},
        { type: 'subtitle', text: 'Conclusión' },
        { type: 'paragraph', text: 'Los controles internos son la base de la auditoria informática. Su correcta implementación es crucial para garantizar la estabilidad, seguridad y continuidad de las operaciones organizacionales.' },
        { type: 'subtitle', text: 'Explotación informática' },
        { type: 'paragraph', text: 'Se ocupa de producir resultados informáticos de todo tipo. Para realizarla se dispone de "los datos", que se someten a controles de integridad y calidad, se transforman mediante el proceso informático gobernado por programas, y finalmente los resultados son sometidos a controles de calidad y distribuidos al cliente.' },
        { type: 'paragraph', text: 'Auditar Explotación consiste en auditar las secciones que componen la producción y sus interrelaciones.' },
        { type: 'subtitle', text: 'AI Explotación - Planificación y recepción de Aplicaciones' },
        { type: 'paragraph', text: 'Se auditaran las normas de entrega de aplicaciones por parte de Desarrollo, verificando su cumplimiento y calidad. Deberán realizarse muestreos selectivos de la documentación. Se inquirirá sobre la anticipación de contactos con desarrollo para la planificación.' },
        { type: 'subtitle', text: 'AI Explotación - Centro de control y seguimiento de trabajos' },
        { type: 'paragraph', text: 'Se analizara como se prepara, se lanza y se sigue la producción diaria. Básicamente, la explotación ejecuta procesos por cadenas o lotes sucesivos (Batch), o en tiempo real. Mientras que las Aplicaciones en Tiempo Real están permanentemente activas, el trabajo batch absorbe una buena parte de los efectivos de explotación.' },
        { type: 'subtitle', text: 'Aplicaciones Batch' },
        { type: 'paragraph', text: 'Son aquellas que procesan la información recolectada durante el día y que durante la noche se ejecutan para relacionar información, realizar cálculos y realizar reportes. Son aplicaciones que realizan procesamientos masivos de información. Es solamente un tema de "Data Entry" que recolecta información, corre el proceso Batch (por lotes), y calcula todo lo necesario para arrancar al día siguiente.' }
    ]
  },
  {
    id: 'drp',
    title: 'Plan de Recuperación ante Desastres (DRP)',
    content: [
      { type: 'subtitle', text: 'Introducción' },
      { type: 'paragraph', text: 'Existen muchos tipos de catástrofes. Toda compañía con tecnologías de información debe tener un plan prediseñado para evitar consecuencias costosas e irreversibles.' },
      { type: 'subtitle', text: 'Experiencias, eventos' },
      { type: 'list', items: [
          { title: 'Naturales', text: 'Terremotos, Tornados, Huracanes, Inundaciones, Pandemias' },
          { title: 'Causadas por el hombre', text: 'Terrorismo, Robo, Sabotaje, Ciberincidentes, Espionaje' }
      ]},
      { type: 'paragraph', text: '¿Somos inmunes a desastres? ¿Pasara aquí? ¿Tenemos una politica de seguros?¿Es suficiente? Nosotros nunca hemos tenido problemas antes.' },
      { type: 'subtitle', text: '¿Por qué implementar un DRP?' },
      { type: 'paragraph', text: 'Referencia a "Sully: Hazaña en el Hudson": "Nada tiene precedentes hasta que pasa por primera vez".' },
      { type: 'subtitle', text: 'Actuación en el caso Sully' },
      { type: 'list', items: ['Avion: Pilotos (Manuales), Sobrecargos (Protocolo)', 'Torre de control: Controlador, Supervisor', '2do Controlador', 'Helicoptero', 'Guardia costera', 'Ferris', 'Cruz Roja'] },
      { type: 'subtitle', text: 'Causas de las perdidas de datos' },
      { type: 'list', items: ['Fallas del Hardware -> 40%', 'Destruccion del Hardware -> 29%', 'Robo -> 13%', 'Virus -> 6%', 'Corrupcion del Software -> 9%', 'Error Humano -> 3%'] },
      { type: 'subtitle', text: 'Otras estadisticas (Boston Computing Network)' },
      { type: 'list', items: ['6% de las pcs sufren algun evento de perdida de datos en cualquier año.', '30% de todas las empresas que tienen un gran incendio, se quedan fuera del mercado en un año.', 'El 31% de los usuarios de pcs han perdido todos sus archivos debido a eventos fuera de su control.', '34% de las empresas no logran probar sus copias de seguridad en cinta, y de las que si lo hacen, el 77% han encontrado problemas.', '60% de las empresas que pierden sus datos, cerraran dentro de los siguientes 6 meses despues del desastre.'] },
      { type: 'subtitle', text: 'Teoria del DRP' },
      { type: 'paragraph', text: '¿Qué es el Dissaster Recovery Planning? Son planes que protegen la informacion, el hardware y el software de un negocio o empresa en alguna anomalia natural o algo causado por una persona. Objetivo: Garantizar la continuidad del negocio.' },
      { type: 'subtitle', text: '¿Por qué hacer un plan de este tipo?' },
      { type: 'list', items: ['Para poder respaldar no solo el procesamiento de informacion, sino tambien las funciones criticas de la compañía', 'Para estar protegido de cualquier tipo de eventuialidad', 'Para evitar perdidas humanas y monetarias', 'Para poder recuperar funcionamiento rapidamente'] },
      { type: 'subtitle', text: 'Fases de un plan de recuperacion de desastres' },
      { type: 'list', items: ['1.- Determinar las necesidades del plan', '2.- Seleccionar al equipo responsable de crearlo', '3.- Identificar planes alternativos para un desastre', '4.- Escribir el plan de recuperacion de desastres', '5.- Probar el plan de recuperacion de desastres', '6.- Capacitar y entrenr al equipo involucrado', '7.- Implementar y evaluar el plan de recuperacion de desastres', '8.- Mantener el plan de recuperacion de desastres'] },
      { type: 'subtitle', text: 'Costos y Beneficios' },
      { type: 'paragraph', text: 'Costos: Seguros, Respaldos, Equipo, Entrenamiento, Comunicación, Suministros.' },
      { type: 'paragraph', text: 'Beneficios: Seguridad funcional, económica, informática y humana.' },
      { type: 'subtitle', text: 'Tipos de sistemas en riesgo' },
      { type: 'list', items: [
          'Estatus crítico: No puede tolerar interrupción.',
          'Estatus vital: Tolera mínima interrupción, necesita actualización casi inmediata.',
          'Estatus sensitivo: Puede ser manejada por medios humanos y tolera un tiempo inhabilitado.',
          'Estatus normal: Puede funcionar de manera semejante a como lo hacia antes del desastre.',
          'Estatus no crítico: Tolera fallas que no generan costos ni secuencias.'
      ]},
      { type: 'subtitle', text: '¿Qué debe de cubrir mi plan?' },
      { type: 'list', items: ['Medidas preventivas', 'Medidas de deteccion', 'Medidas de correcion'] },
      { type: 'subtitle', text: '¿Cómo debo realizar mi estrategia de recuperacion ante desastres?' },
      { type: 'paragraph', text: 'Identificar los puntos criticos de la operación y el tiempo aceptable de inactividad. A mayor criticidad y menor tolerancia, mayor será la inversión.' },
      { type: 'subtitle', text: '¿Qué debo incluir en mi plan?' },
      { type: 'list', items: ['Servidores espejo locales', 'Proteccion de tension electrica', 'Sistemas UPS', 'Proteccion contra fuego', 'Antivirus', 'Seguridad de redes', 'Respaldos contantes (dentro y fuera de sitio)', 'Soluciones de Alta Disponibilidad', 'Replica de informacion'] },
      { type: 'subtitle', text: '9 pasos para construir un plan de recuperación de desastres' },
      { type: 'list', items: [
        { title: '1. Haga un inventario de activos', text: 'Liste todos los activos de TI, su ubicación física, red y dependencias.' },
        { title: '2. Evalué riesgos', text: 'Liste amenazas internas y externas para cada activo. Incluya probabilidad e impacto.' },
        { title: '3. Defina la criticidad de las aplicaciones y los datos', text: 'Clasifique datos y aplicaciones según su criticidad para el negocio.' },
        { title: '4. Defina los objetivos de recuperación', text: 'Establezca RTO y RPO para diferentes clases de datos.' },
        { title: '5. Determine las herramientas y técnicas adecuadas', text: 'Elija el nivel de protección adecuado sin sobreproteger (costoso) ni subproteger (riesgoso).' },
        { title: '6. Obtenga la participación de los interesados', text: 'Involucre a los dueños de aplicaciones y negocios. Consiga un patrocinador ejecutivo.' },
        { title: '7. Documente y comunique su plan', text: 'Un plan documentado asegura la secuencia correcta y evita omisiones en un escenario de desastre.' },
        { title: '8. Pruebe y practique su plan de DR', text: 'La práctica ayuda a encontrar y rectificar problemas en el plan.' },
        { title: '9. Evalué y actualice su plan', text: 'Un plan de DR debe ser un documento vivo que refleje el estado actual de la organización.' }
      ]},
      { type: 'subtitle', text: 'Tiempo de recuperación objetivo (RTO)' },
      { type: 'paragraph', text: '¿Cuál es el tiempo aceptable de indisponibilidad? Para calcularlo, considere la cantidad de ingresos que su organización perdería.' },
      { type: 'subtitle', text: 'Objetivo de punto de recuperación (RPO)' },
      { type: 'paragraph', text: '¿Cuál es la cantidad aceptable de datos que su organización puede perder? El RPO determina la frecuencia mínima de las copias de seguridad.' }
    ]
  },
  {
    id: 'vyv',
    title: 'Verificación y Validación',
    content: [
      { type: 'subtitle', text: 'Ciclo de Vida de Software y Pruebas' },
      { type: 'paragraph', text: 'Fases: Analisis Requerimientos, Arquitectura, Diseño, Programacion, Pruebas unitarias, Pruebas de integracion, Pruebas del sistema, Pruebas de aceptacion, Implantacion.' },
      { type: 'subtitle', text: 'Pruebas de software - Verificación y Validación' },
      { type: 'list', items: [
          { title: 'Estructural (Caja blanca)', text: 'Eficiencia del codigo, Complejidad ciclomatica, Legibilidad, Comentarios, Identacion, Estructura, Nomenclatura, Documentacion, Codigo muerto.' },
          { title: 'Funcional (Caja negra)', text: 'Se puede hacer reingeniería del proceso.' }
      ]},
      { type: 'subtitle', text: 'Proceso de Pruebas' },
      { type: 'list', items: ['Diseño de casos de prueba', 'Ejecución de casos de prueba', 'Registro de defectos', 'Corrección de defectos', 'Verificacion de la correccion', 'Análisis del proceso y métricas', 'Proceso de mejora'] },
      { type: 'subtitle', text: 'Técnicas de Diseño de Casos de Prueba (Caja Negra)' },
      { type: 'list', items: ['Clases de equivalencia', 'Valores límite', 'Grafos causa-efecto'] },
      { type: 'subtitle', text: 'Matriz de control de defectos' },
      { type: 'paragraph', text: 'Cuando se identifican defectos, se registran en una matriz con campos como:' },
      { type: 'list', items: ['ID del defecto', 'Tester', 'Descripcion', 'Fecha de registro', 'Evidencia', 'Estatus', 'Programador', 'Fase de inyeccion', 'Fase de deteccion', 'Prioridad', 'Severidad', 'Repetibilidad', 'Dispositivo', 'Version', 'Tipo de defecto'] },
    ]
  },
  {
    id: 'pareto_ishikawa',
    title: 'Pareto 80/20 e Ishikawa',
    content: [
      { type: 'subtitle', text: '¿Qué es el principio de Pareto?' },
      { type: 'paragraph', text: 'El principio de Pareto, también conocido como la regla del 80/20, es un concepto que establece que, para muchos eventos, aproximadamente el 80% de los efectos provienen del 20% de las causas. Ejemplos: 80% de las ventas proviene del 20% de los clientes; 80% de los errores se originan en el 20% de los procesos.' },
      { type: 'subtitle', text: 'Aplicación del Principio de Pareto en Procesos de Mejora' },
      { type: 'list', items: [
          { title: '1. Análisis del Problema', text: 'Identificar y clasificar los efectos no deseados (problemas, errores) según su frecuencia o impacto para priorizar.' },
          { title: '2. Identificación de Causas', text: 'Una vez identificados los problemas principales, analizar sus causas raíz, a menudo usando un diagrama de Ishikawa.' },
          { title: '3. Generación de Acciones de Mejora', text: 'Desarrollar e implementar acciones correctivas enfocadas en las causas más significativas.' }
      ]},
      { type: 'subtitle', text: 'Diagrama de Ishikawa: Análisis de Causas para la Mejora Continua' },
      { type: 'paragraph', text: 'También conocido como diagrama de causa-efecto o de espina de pescado, es una herramienta gráfica que permite organizar visualmente las posibles causas de un problema, agrupándolas en categorías.' },
      { type: 'list', items: [
          { title: 'Cabeza del pez', text: 'Representa el problema o efecto no deseado.' },
          { title: 'Espinas principales', text: 'Representan las categorías generales de causas (ej. 6M).' },
          { title: 'Subespinas', text: 'Detallan causas específicas dentro de cada categoría.' }
      ]},
      { type: 'subtitle', text: 'Categorías Clásicas (Las 6M)' },
      { type: 'list', items: ['Mano de obra (Manpower)', 'Máquinas (Machines)', 'Métodos (Methods)', 'Materiales (Materials)', 'Medio ambiente (Environment)', 'Medición (Measurement)'] },
      { type: 'subtitle', text: 'Análisis de Defectos de Software con Diagrama de Ishikawa' },
      { type: 'paragraph', text: 'Se pueden adaptar las categorías al ciclo de vida del software:' },
      { type: 'list', items: ['Requerimientos', 'Diseño', 'Codificación', 'Pruebas', 'Herramientas y Entorno', 'Gestión del Proyecto'] },
      { type: 'paragraph', text: 'Este análisis ayuda a identificar causas raíz, como ambigüedad en requerimientos o falta de revisiones de código, y a proponer acciones de reingeniería, como refactorizar un módulo o mejorar el proceso de desarrollo.' }
    ]
  },
  {
    id: 'caja_blanca',
    title: 'Pruebas de Caja Blanca y Grafos de Flujo',
    content: [
      { type: 'subtitle', text: 'Análisis del Código Fuente' },
      { type: 'paragraph', text: 'Las pruebas de caja blanca se enfocan en la estructura interna del código, verificando que sea:' },
      { type: 'list', items: ['Documentado', 'Estructurado (indentación, nomenclatura)', 'Sin código muerto', 'Eficiente y Seguro (no vulnerable a SQL Injection, etc.)'] },
      { type: 'subtitle', text: 'Complejidad Ciclomática' },
      { type: 'paragraph', text: 'Es una métrica de calidad de software que mide la cantidad de caminos linealmente independientes a través del código fuente de un programa. Sirve para determinar el número mínimo de casos de prueba necesarios para cubrir toda la lógica.' },
      { type: 'table',
        headers: ['Complejidad', 'Tipo de programa', 'Riesgo'],
        rows: [
          ['1-10', 'Simple', 'Bajo'],
          ['11-20', 'Moderado', 'Moderado'],
          ['21-50', 'Complejo', 'Alto Riesgo'],
          ['>50', 'Muy complejo', 'Muy alto riesgo (No testeable)']
        ]
      },
      { type: 'paragraph', text: 'Consejo: Agrupar en bloques las secuencias de sentencias simples para reducir la complejidad.' }
    ]
  }
]; 